dataRoot: ./data
listen: true
port: 8000
server:
  host: 0.0.0.0
whitelistMode: false
enableForwardedWhitelist: true
whitelist:
  - 0.0.0.0
basicAuthMode: true
basicAuthUser:
  username: xellss
  password: Chaucer@1
enableCorsProxy: false
enableUserAccounts: false
enableDiscreetLogin: false
cookieSecret: NO/PCCOfBz60yQA/9eC1PF6dhdqlzYobVaZVppmGDxt72UgEQtzzyfnjxVzsi85VmflkyVAaY7+lutOTccB6SQ==
disableCsrfProtection: false
securityOverride: false
autorun: true
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: true
skipContentCheck: false
disableChatBackup: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
enableExtensions: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
